### ISSUE TITLE
cronjob.yaml for >= 1.8 kubernetes clusters

### ISSUE THREAD

**Issue by cmanikandan** [aws-samples/aws-workshop-for-kubernetes#361]
Since most current kubernetes clusters are >= 1.8, we should probably use "apiVersion: batch/v1beta1" in cronjob.yaml and not use the --validate=false option

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: hello-cronpod
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello World!
          restartPolicy: OnFailure
```
