### ISSUE TITLE
201 - Prometheus not loading any metrics.

### ISSUE THREAD

**Issue by andrewhertog** [aws-samples/aws-workshop-for-kubernetes#491]

**Comment by CharlyF** [comment]
I also hit this issue - You can just `kubectl edit clusterrole prometheus-operator -n monitoring`
and add the missing verbs, in your case `list` for endpoints/svcs and `watch` for pods I think.
This is the RBAC that got the UI up in my case.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
[...]
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
  - list
  - create
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
```

Interestingly, these are not required according to the doc of [0.14.1](https://github.com/coreos/prometheus-operator/blob/v0.14.1/Documentation/rbac.md#prometheus-operator-rbac)
